package com.demo.gym.repository;
import com.demo.gym.gym.GymRepository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.demo.gym.common.Address;
import com.demo.gym.gym.Gym;
import com.demo.gym.gym.GymType;
import com.demo.gym.GymApplication;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.persistence.autoconfigure.EntityScan;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.test.context.ContextConfiguration;

@DataJpaTest
@ContextConfiguration(classes = GymApplication.class)
@EnableJpaRepositories(basePackages = {"com.demo.gym.gym", "com.demo.gym.member"})
@EntityScan(basePackages = {"com.demo.gym.visit", "com.demo.gym.gym", "com.demo.gym.member", "com.demo.gym.billing", "com.demo.gym.common"})
public class GymRepositoryTest {

    @Autowired
    private GymRepository repository;

    @Test
    void shouldSaveAndRetrieveGym() {
        final String name = "Gym";
        final Address address = new Address("Country", "City", "Street", "444");

        Gym gym = createValidGym("112", name, address);

        Gym savedGym = repository.save(gym);

        assertThat(savedGym.getId()).isNotNull(); // ID should be generated by SEQUENCE
        assertThat(savedGym.getName()).isEqualTo(name);

        Gym found = repository.findById(savedGym.getId()).orElseThrow();
        assertThat(found.getAddress()).isEqualTo(address);
    }

    @Test
    void shouldThrowExceptionWhenGymTaxIdIsDuplicate() {
        final String sameTaxId = "111";
        final Address address = new Address("Country", "City", "Street", "444");

        Gym h1 = createValidGym(sameTaxId, "test1", address);
        repository.saveAndFlush(h1);

        Gym h2 = createValidGym(sameTaxId, "test2", address);

        assertThrows(DataIntegrityViolationException.class, () -> repository.saveAndFlush(h2));
    }

    @Test
    void shouldFailWhenNameIsNull() {
        Gym gym = createValidGym("112", null, null); // Name is null

        assertThrows(DataIntegrityViolationException.class, () -> repository.saveAndFlush(gym));
    }

    private Gym createValidGym(String taxId, String name, Address address) {
        var gym = new Gym();
        gym.setTaxId(taxId);
        gym.setName(name);
        gym.setType(GymType.PUBLIC);
        gym.setEmail("contact@gym.com");
        gym.setWebsiteUrl("www.gym.com");
        gym.setPhoneNumber("123-456");
        gym.setCapacity(200);
        gym.setAddress(address);
        return gym;
    }
}
